# configs/iso_config.yaml

pricing:
  default_buy_price: 20.0  
  default_sell_price: 0.0  
  parameters:
    min_price: 0.0
    max_price: 20.0

# Enable dispatch action
dispatch:
  use_dispatch_action: true
  parameters:
    min: 0.0
    max: 300.0

# Action space configurations for different pricing policies
action_spaces:
  quadratic:
    dispatch:
      min: 0.0
      max: 300.0
    polynomial:
      min: 0.0
      max: 0.1
  online:
    buy_price:
      min: 1.0
      max: 10.0
    sell_price:
      min: 1.0
      max: 10.0
    dispatch:
      min: 0.0
      max: 300.0

# Observation space configuration
observation_space:
  time:
    min: 0.0
    max: 1.0
  predicted_demand:
    min: 0.0
    max: inf  # represents np.inf
  pcs_demand:
    min: -inf  # represents -np.inf
    max: inf   # represents np.inf

# Specifies which ISO implementation to use
type: "HourlyPricingISO"

# Parameters specific to the chosen ISO
parameters:
  # For HourlyPricingISO
  hourly_rates:
    0: 4.0
    1: 4.0
    2: 4.0
    3: 4.0
    4: 4.0
    5: 5.0
    6: 6.0
    7: 6.0
    8: 5.5
    9: 5.0
    10: 5.0
    11: 5.5
    12: 6.0
    13: 6.0
    14: 5.5
    15: 5.0
    16: 5.0
    17: 5.5
    18: 6.0
    19: 6.0
    20: 5.5
    21: 5.0
    22: 4.5
    23: 4.0

